app/build.gradle.kts
app/src/main/java/com/goldenraven/padawanwallet/PadawanWalletApplication.kt
app/src/main/java/com/goldenraven/padawanwallet/data/Repository.kt
app/src/main/java/com/goldenraven/padawanwallet/data/Wallet.kt
app/src/main/java/com/goldenraven/padawanwallet/drawer/DrawerActivity.kt
app/src/main/java/com/goldenraven/padawanwallet/drawer/SeedPhraseFragment.kt
app/src/main/java/com/goldenraven/padawanwallet/drawer/SettingsFragment.kt
app/src/main/java/com/goldenraven/padawanwallet/intro/IntroFragment.kt
app/src/main/java/com/goldenraven/padawanwallet/intro/WalletRecoveryFragment.kt
build.gradle.kts

Removed timber for logging and replaced with Log 
Solves #110

Removed Timber for logging and replaced with Log

---

README.md

Added build Instructions

---

app/src/main/java/com/goldenraven/padawanwallet/drawer/SendCoinsBackFragment.kt

Solves issue #160
Using same solution as mentioned in #161

Fix: Using snackbar to confirm address copied on SendCoinsBackFragment.kt

---

app/src/main/java/com/goldenraven/padawanwallet/data/Repository.kt
app/src/main/java/com/goldenraven/padawanwallet/wallet/tutorials/TutorialsHome.kt

Fixes #88 by Added a flag to **Repository.kt** so that when user resets their tutorials **TutorialsHome.kt** fragment will check for and update UI if necessary. 
I think this is the simplest fix unless its easier to redraw the **TutorialsHome.kt** fragment.

Fix: reset done tutorials requires app restart #88

---

app/src/main/java/com/goldenraven/padawanwallet/wallet/wallet/WalletBuild.kt

Fix: Use chosen fee rate for creating psbt

---

app/src/main/java/com/goldenraven/padawanwallet/wallet/wallet/WalletHome.kt

Fixes #127 by calling a coroutine in the `onCreateView` so the view only calls it once on startup.
Fixes #139 by calling the snackbar using the `rootView` instead of the child view, so switching fragments will not cause it to crash the app.

Fix: Sync wallet on startup and stop crashing when changing tabs during sync

---

app/src/main/java/com/goldenraven/padawanwallet/wallet/wallet/WalletBuild.kt
app/src/main/res/layout/fragment_wallet_build.xml
app/src/main/res/values/strings.xml

This PR is to add a new feature of the slider to choose transaction fees while sending bitcoins.
issue #125

Added the slider for fee selection

---

app/src/main/java/com/goldenraven/padawanwallet/ui/tutorials/TutorialsScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletNavigation.kt

Adding the individual tutorial content to the screens. I have hard-coded retrieving the content for each of the screens, since I'm not sure if theres a better, more scalable way to handle this. 
The title and headers are centered, and the paragraphs are aligned left.

Feature: Adding Indiv Tutorials

---

app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/SendScreen.kt

Feature for #204
Changed input verification to reflect incorrect field.
Broadcast BDK error during broadcast

Feat: Verify input before broadcast

---

app/build.gradle.kts
app/src/androidTest/java/com/goldenraven/padawanwallet/intro/WalletRecoveryScreenTest.kt
app/src/main/java/com/goldenraven/padawanwallet/HomeNavigation.kt
app/src/main/java/com/goldenraven/padawanwallet/data/Wallet.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/drawer/AboutScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/drawer/RecoveryPhraseScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/drawer/SendCoinsBackScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/drawer/SettingsScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/ReceiveScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletScreen.kt
app/src/test/java/com/goldenraven/padawanwallet/data/RepositoryTest.kt

Feat #210 . Migrated current padawan wallet to use `bdk-android 0.7.0`. 
Added check for internet connection before creating new `blockchain` object to prevent any issues with no internet connection. 
More work can be done for handling on / off network connections during app use.

Feat_Upgrade_BDK_0_7_0

---

app/src/main/java/com/goldenraven/padawanwallet/ui/settings/SettingsRootScreen.kt

Fix #256 When chapter reset button is clicked snackbar shows up to indicate success.

Feat: Add snackbar to show chapters reset was successful

---

app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/ReceiveScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletViewModel.kt

Fixes #301

---

app/src/main/java/com/goldenraven/padawanwallet/ui/chapters/ChapterScreen.kt

[WIP] Make Finish button the same size as Previous and Next

---

app/src/main/java/com/goldenraven/padawanwallet/theme/Modifiers.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/Composables.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/Screen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/chapters/ChapterScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/chapters/ChaptersRootScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/settings/RecoveryPhraseScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/settings/SendCoinsBackScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/settings/SettingsRootScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/ReceiveScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/SendScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/TransactionScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletRootScreen.kt

Fixes some of the issues in #282.

Fix issues with small screens

---

app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletNavigation.kt

Fix: Fix the QR scanner transition

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ContentView.swift
iosApp/iosApp/LearnView.swift
iosApp/iosApp/MenuView.swift
iosApp/iosApp/WalletView.swift
iosApp/iosApp/WalletViewModel.swift

-Refactor: separate view files and update content of views

Refactor: Separate views into individual files

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp/ContentView.swift
iosApp/iosApp/MenuView.swift
iosApp/iosApp/ReceiveView.swift
iosApp/iosApp/SendView.swift
iosApp/iosApp/WalletView.swift

Refactor: Modify Wallet View to use Navigation Stack
UI: Add send and receive buttons
UI: Add receive View

UI: Add receive view

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iosApp/iosApp/ContentView.swift
iosApp/iosApp/LearnView.swift
iosApp/iosApp/ReceiveView.swift
iosApp/iosApp/RecoverView.swift
iosApp/iosApp/WalletView.swift
iosApp/iosApp/WalletViewModel.swift
iosApp/iosApp/WelcomeView.swift
iosApp/iosApp/iOSApp.swift

feat: add ability to create or recover wallet
ui: update transactions view as per BDKswiftExampleWallet
chore: optimize sync and load methods
chore: update BDK to latest version

feat: add ability to create or recover wallet

---

iosApp/iosApp/ContentView.swift
iosApp/iosApp/LearnView.swift
iosApp/iosApp/MenuView.swift
iosApp/iosApp/ReceiveView.swift
iosApp/iosApp/RecoverView.swift
iosApp/iosApp/SendView.swift
iosApp/iosApp/WalletView.swift
iosApp/iosApp/WalletViewModel.swift
iosApp/iosApp/WelcomeView.swift
iosApp/iosApp/iOSApp.swift

UI: pressing Done in Receive will return to main wallet view
chore: update file headers for Apache 2.0 license

UI: pressing done in Receive will return to main wallet view

---

iosApp/iosApp/SendView.swift

UI: update the send view

---

iosApp/iosApp.xcodeproj/project.pbxproj
iosApp/iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iosApp/iosApp/WalletView.swift

chore: update bdk version to fix an xcode bug preventing the simulator and preview from working
fix: prevent transactions list from crashing

Bump BDK version

---

androidApp/src/main/res/values-pt/chapter1.xml
androidApp/src/main/res/values-pt/chapter2.xml

The english texts ware translated to portuguese.

Translate to portuguese Chapter1.xml

---

iosApp/iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
iosApp/iosApp/ContentView.swift
iosApp/iosApp/WalletView.swift
iosApp/iosApp/WalletViewModel.swift

UI: Add Faucet view
UI: Add Transaction Details view (copied from BDKSwiftExampleWallet)
Task: Bump minimum iOS and Xcode versions to latest

UI: Add Faucet view

---

.gitignore
PadawanWalletiOS/PadawanWallet.xcodeproj/project.pbxproj
PadawanWalletiOS/PadawanWallet.xcodeproj/project.xcworkspace/contents.xcworkspacedata
PadawanWalletiOS/PadawanWallet.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
PadawanWalletiOS/PadawanWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PadawanWalletiOS/PadawanWallet/Assets.xcassets/AccentColor.colorset/Contents.json
PadawanWalletiOS/PadawanWallet/Assets.xcassets/AppIcon.appiconset/Contents.json
PadawanWalletiOS/PadawanWallet/Assets.xcassets/Contents.json
PadawanWalletiOS/PadawanWallet/ContentView.swift
PadawanWalletiOS/PadawanWallet/LearnView.swift
PadawanWalletiOS/PadawanWallet/MenuView.swift
PadawanWalletiOS/PadawanWallet/PadawanWalletApp.swift
PadawanWalletiOS/PadawanWallet/Preview Content/Preview Assets.xcassets/Contents.json
PadawanWalletiOS/PadawanWallet/ReceiveView.swift
PadawanWalletiOS/PadawanWallet/RecoverView.swift
PadawanWalletiOS/PadawanWallet/SendView.swift
PadawanWalletiOS/PadawanWallet/WalletView.swift
PadawanWalletiOS/PadawanWallet/WalletViewModel.swift
PadawanWalletiOS/PadawanWallet/WelcomeView.swift
PadawanWalletiOS/PadawanWalletTests/PadawanWalletTests.swift
PadawanWalletiOS/PadawanWalletUITests/PadawanWalletUITests.swift
PadawanWalletiOS/PadawanWalletUITests/PadawanWalletUITestsLaunchTests.swift
androidApp/build.gradle.kts
padawankmp/build.gradle.kts
padawankmp/src/commonMain/kotlin/com/goldenraven/padawanwallet/padawankmp/Greeting.kt
settings.gradle.kts

Set the stage for building an iOS dependency called PadawanKmp.

Padawan kmp

---

androidApp/src/main/res/values-pt/chapter4.xml

Translate to portuguese Chapter4.xml

chapter4.xml

---

PadawanWalletiOS/PadawanWallet.xcodeproj/project.pbxproj
PadawanWalletiOS/PadawanWallet/Extensions/BDKError+Extensions.swift
PadawanWalletiOS/PadawanWallet/Extensions/Int+Extensions.swift
PadawanWalletiOS/PadawanWallet/Extensions/String+Extensions.swift
PadawanWalletiOS/PadawanWallet/SendView.swift
PadawanWalletiOS/PadawanWallet/WalletView.swift
PadawanWalletiOS/PadawanWallet/WalletViewModel.swift

feat: add verify and send functionality
refactor: move Class extensions from view model to separate files

feat: add send and verify functionality

---

PadawanWalletiOS/PadawanWallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
PadawanWalletiOS/PadawanWallet/ContentView.swift
PadawanWalletiOS/PadawanWallet/LearnView.swift
PadawanWalletiOS/PadawanWallet/MenuView.swift
PadawanWalletiOS/PadawanWallet/PadawanWalletApp.swift
PadawanWalletiOS/PadawanWallet/ReceiveView.swift
PadawanWalletiOS/PadawanWallet/RecoverView.swift
PadawanWalletiOS/PadawanWallet/SendView.swift
PadawanWalletiOS/PadawanWallet/WalletView.swift
PadawanWalletiOS/PadawanWallet/WalletViewModel.swift
PadawanWalletiOS/PadawanWallet/WelcomeView.swift

refactor: switch to iOS17 Observation for managing model data

refactor: switch to iOS17 Observation

---

PadawanWalletiOS/Localizable.xcstrings
PadawanWalletiOS/PadawanWallet.xcodeproj/project.pbxproj
PadawanWalletiOS/PadawanWallet.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
PadawanWalletiOS/PadawanWallet/ContentView.swift
PadawanWalletiOS/PadawanWallet/ReceiveView.swift
PadawanWalletiOS/PadawanWallet/RecoverView.swift
PadawanWalletiOS/PadawanWallet/SendView.swift
PadawanWalletiOS/PadawanWallet/WalletView.swift
PadawanWalletiOS/PadawanWallet/WelcomeView.swift

feat: add language localization to support more than one language

feat: add language localization

---

androidApp/build.gradle.kts
androidApp/src/main/java/com/goldenraven/padawanwallet/PadawanWalletApplication.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/domain/bitcoin/TransactionDetails.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/domain/bitcoin/Wallet.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/domain/tx/Tx.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/domain/tx/TxDatabase.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/domain/tx/TxRepository.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/presentation/navigation/WalletNavigation.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/presentation/ui/PadawanActivity.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/presentation/ui/screens/wallet/SendScreen.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/presentation/ui/screens/wallet/TransactionScreen.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/presentation/ui/screens/wallet/WalletRootScreen.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/presentation/viewmodels/ReceiveViewModel.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/presentation/viewmodels/WalletViewModel.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/presentation/viewmodels/mvi/MviWalletScreens.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/utils/DatabaseUtils.kt
androidApp/src/main/java/com/goldenraven/padawanwallet/utils/Screen.kt
androidApp/src/main/res/values-es/strings.xml
androidApp/src/main/res/values-pt/strings.xml
androidApp/src/main/res/values/strings.xml

Chore: Update bdk-android to 1.0.0-alpha.13

---

iOS/PadawanWallet/App/PadawanWalletApp.swift
iOS/PadawanWallet/Features/Onboarding/OnboardingView.swift
iOS/PadawanWallet/Theme/UI Components/Buttons/PadawanButton.swift
iOS/PadawanWallet/Theme/UI Components/Common/BackgroundView.swift

Create the OnboardingView interface

[iOS]: Added onboarding interface

---

.gitignore
README.md
iOS/PadawanWallet/Common/Service/BDK Service/BDKService.swift
iOS/PadawanWallet/Features/Wallet/Components/BalanceCard.swift
iOS/PadawanWallet/Features/Wallet/Components/TransactionCard.swift
iOS/PadawanWallet/Features/Wallet/WalletView.swift
iOS/PadawanWallet/Features/Wallet/WalletViewModel.swift
iOS/PadawanWallet/Resources/Config/AppConfig.xcconfig
iOS/PadawanWallet/Theme/UI Components/Buttons/PadawanButton.swift
iOS/PadawanWallet/Theme/UI Components/Common/AlertModalView.swift
iOS/project.yml

It adds the Faucet coins service to the home screen.

[iOS]: add Faucet coins service

---

README.md
iOS/PadawanWallet/Features/Wallet/WalletViewModel.swift
iOS/project.yml

Just update the faucet auth method

[iOS] updated the faucet authentication method
