app/src/main/java/com/goldenraven/padawanwallet/wallet/wallet/WalletBuild.kt
app/src/main/res/layout/fragment_wallet_build.xml

Adjustable fee rate for transactions

---

app/build.gradle.kts
app/src/main/java/com/goldenraven/padawanwallet/data/TxDao.kt
app/src/main/java/com/goldenraven/padawanwallet/utils/Timestamp.kt
app/src/main/java/com/goldenraven/padawanwallet/wallet/TxHistoryAdapter.kt
app/src/main/java/com/goldenraven/padawanwallet/wallet/WalletViewModel.kt
app/src/main/java/com/goldenraven/padawanwallet/wallet/wallet/WalletBuild.kt

Migrate bitcoindevkit dependency to v0.3.0-rc1

---

app/src/main/java/com/goldenraven/padawanwallet/intro/IntroFragment.kt
app/src/main/res/values/strings.xml

Fixes #155 
Strings migrated to `strings.xml` as:
```
<string name="intro_dialog_message">...</string>
<string name="intro_dialog_title">...</string>
<string name="intro_dialog_positive">...</string>
<string name="intro_dialog_negative">...</string>
```

removed hard-coded strings from IntroFragment.kt

---

app/src/main/java/com/goldenraven/padawanwallet/wallet/wallet/WalletReceive.kt

Fixes #50 Copy address button in the receive tab will now use the _fireSnackbar_ util. It will show _"Generate new address first!"_ if no address was generated when copying and _"Copied address to clipboard!"_ when user copies normally.

Fix: Using snackbar instead of toast when copying address #50

---

app/src/main/java/com/goldenraven/padawanwallet/data/TxDatabase.kt

Fixes #171 by adding a `.fallbackToDestructiveMigration()` method during the DB creation so users with old DB versions will have them cleared and recreated.

Fix: Users with old DB will not crash on launch

---

app/src/main/java/com/goldenraven/padawanwallet/HomeScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/Screen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/tutorials/TutorialsHomeScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/tutorials/TutorialsScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletNavigation.kt

Removed `@OptIn(ExperimentalMaterial3Api::class)` from `HomeScreen.kt` since it is already called at the start of the class.
Added `innerPadding` to the `BottomBar` so that it does not cover the contents in the main screen.
Refactored current `TutorialsScreen` to `TutorialsHomeScreen`.
Added `TutorialsHomeScreen` to show list of all tutorials, and each is clickable to the `TutorialsScreen` with the `tutorialId` as an argument.

Feature: Adding basic tutorial home

---

.github/workflows/android_build.yaml

Moved the CI changes to this PR. The changes are just additions to the `android_build.yaml` file.

Feature: Adding CI integration tests to android_build.yaml

---

app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletNavigation.kt

Fixes #196. 
Changing the start and end animtion of the tutorial so that it will start from bottom to top, then end from top to bottom.

Feat: Changing Tutorial sliding animation

---

app/src/main/java/com/goldenraven/padawanwallet/HomeNavigation.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/drawer/RecoveryPhraseScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/drawer/SendCoinsBackScreen.kt
app/src/main/res/values/strings.xml

Added drawer screens for `RecoveryPhraseScreen.kt` and `SendCoinsBackScreen.kt`.
Standardized the animations for every drawer screen.
In the `SendCoinsBackScreen.kt` I have used the general snackbar but it can be changed later on.

Feat: Added 2 drawer screens

---

app/src/main/java/com/goldenraven/padawanwallet/ui/drawer/SendCoinsBackScreen.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/drawer/SettingsScreen.kt
app/src/main/res/values/strings.xml

Added simple settings page with the `Request Testnet Coins!` button. Code is largely the same as the previous settings fragment but the deprecated auth method has been changed. 
I also moved the snackbar in the `SendCoinsBackScreen.kt` to the bottombar of the scaffold.

Feat: Added simple settings page

---

app/build.gradle.kts

Fix #211 Changed the `androidx.camera:camera-view` dependency to align with the other camerax dependencies.

Fix: QR Scanner Crash

---

app/src/main/java/com/goldenraven/padawanwallet/ui/settings/AboutScreen.kt
app/src/main/res/values/strings.xml

Made privacy policy link clickable

---

app/src/main/java/com/goldenraven/padawanwallet/ui/settings/SendCoinsBackScreen.kt

Fixes #241, #201 
**Screenshot:**

Show copied to clipboard snackbar

---

CONTRIBUTING.md

I have added a Code of conduct along with Contributing guidelines to the project. In my Contributing guideline, I have not provided a link for the IHR Code of conduct, in case this gets merged I would add the link else the link would redirect to my repo. Let me know what you think about the rules and approach I have provided. @thunderbiscuit sir incase you need some changes let me know I would make and send the PR again.
Solved issue https://github.com/thunderbiscuit/padawan-wallet/issues/245

Docs: Add CONTRIBUTING.md file

---

app/src/main/java/com/goldenraven/padawanwallet/ui/settings/SendCoinsBackScreen.kt
app/src/main/res/drawable/ic_checked.xml
app/src/main/res/values/strings.xml

fixed: #262 
The icon and text remain the same even after copying the key.
implemented the text from "copy" to "copied' and the default icon with a check icon and then reset to the default text and icon after a short delay.
How it looks in-app : 
https://user-images.githubusercontent.com/73611313/224526390-2e41e8cf-ed58-4d9a-977d-55ca516e0d16.mp4

Feat: Change copy icon and text after clicked

---

app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletRootScreen.kt

Fixes #257 Displays the amount as mentioned in https://medium.com/@mark.nugent.iv/grouping-bitcoins-fractional-digits-an-idea-whose-time-has-come-22d9dad8ac51
**Screenshots:**

Display amount in accepted standard

---

app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/WalletRootScreen.kt

Sync button touches the card's bottom edge

---

app/src/main/java/com/goldenraven/padawanwallet/ui/wallet/ReceiveScreen.kt

Fix: Generate address qr in suspended thread

---

app/src/main/java/com/goldenraven/padawanwallet/ui/chapters/ChapterScreen.kt

Fixes #296 
Now the `Finish` button is the same size as the other buttons.

Increase finish button padding

---

app/src/main/java/com/goldenraven/padawanwallet/data/chapters/ChapterData.kt
app/src/main/java/com/goldenraven/padawanwallet/ui/chapters/ChaptersRootScreen.kt

UI: Clean up the UI for selected/completed chapters in carousel

---

androidApp/src/main/res/values-pt/chapter3.xml

The english texts ware translated to portuguese.

Translate to portuguese Chapter3.xml

---

localization/scripts/build-xcstrings.py

When I ran `build-xcstrings.py` on my machine, I got the following error
```
The python scritp wans't localizing ios/Localizable.xcstrings because the script was not creating the directory before use
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/repos/Open/padawan-wallet/localization/scripts/../ios/Localizable.xcstrings
```
I added a command to `build-xcstrings.py` to create the `ios` directory before attempting to write the `Localizable.xcstrings` file.

fix: create ios directory before generating Localizable.xcstrings

---

iOS/PadawanWallet/Features/Onboarding/OnboardingView.swift
iOS/PadawanWallet/Resources/Fonts/Fonts+Util.swift
iOS/PadawanWallet/Theme/UI Components/Buttons/FilledButton.swift
iOS/PadawanWallet/Theme/UI Components/Buttons/PadawanButton.swift
iOS/PadawanWallet/Theme/UI Components/PadawanButton.swift

Created Padawan and FilledButton to use across the app
**PadawanButton**
**FilledButton**

[iOS]: Added PadawanButton and FilledButton
